# yamllint disable rule:line-length
---
name: SonarCloud Scan
description: Runs SonarCloud scan with optional coverage report and quality gate check

inputs:
  sonar-token:
    description: 'SonarCloud token.'
    required: true
  github-token:
    description: 'GitHub token for PR decoration.'
    required: true
  org-gh-token:
    description: 'Org GitHub token for checkout.'
    required: true
  coverage-path:
    description: 'Path to coverage file. If empty, only the lint report is uploaded.'
    required: false
    default: ''
  check-quality-gate:
    description: 'Whether to enforce the SonarCloud quality gate after the scan.'
    required: false
    default: 'false'
  quality-gate-name:
    description: 'Override the quality gate used for this scan (e.g. "Just lint"). If empty, the project default is used.'
    required: false
    default: ''
  event-name:
    description: 'GitHub event name (github.event_name).'
    required: true
  pr-number:
    description: 'Pull request number.'
    required: false
    default: ''
  head-ref:
    description: 'PR head branch name.'
    required: false
    default: ''
  base-ref:
    description: 'PR base branch name.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: TykTechnologies/github-actions/.github/actions/checkout-pr@main
      with:
        token: ${{ inputs.org-gh-token }}

    - name: Download golangcilint artifacts
      uses: actions/download-artifact@v4
      with:
        name: golangcilint

    - name: Download coverage artifacts
      if: ${{ inputs.coverage-path != '' }}
      uses: actions/download-artifact@v4
      with:
        name: coverage

    - name: Check reports existence
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.coverage-path != '' && format('{0}, golangci-lint-report.json', inputs.coverage-path) || 'golangci-lint-report.json' }}
        fail: true

    - name: Set SonarCloud parameters
      id: sonar_params
      shell: bash
      run: |
        SONAR_ARGS="-Dsonar.organization=tyktechnologies \
        -Dsonar.projectKey=TykTechnologies_tyk \
        -Dsonar.sources=. \
        -Dsonar.exclusions=**/testdata/*,test/**,tests/**,coprocess/**/*,ci/**,templates/**,**/*.pb.go,internal/graphengine/gomock_reflect_3503306920/*,**/*.gen.go \
        -Dsonar.coverage.exclusions=**/*_test.go,**/*_mock.go,**/mock/*,tests/**,swagger*.yml,**/*.pb.go,internal/graphengine/gomock_reflect_3503306920/* \
        -Dsonar.test.inclusions=**/*_test.go,tests/** \
        -Dsonar.tests=. \
        -Dsonar.go.golangci-lint.reportPaths=golangci-lint-report.json"

        if [[ "${{ inputs.coverage-path }}" != "" ]]; then
          SONAR_ARGS="$SONAR_ARGS \
          -Dsonar.go.coverage.reportPaths=${{ inputs.coverage-path }}"
        fi

        if [[ "${{ inputs.quality-gate-name }}" != "" ]]; then
          SONAR_ARGS="$SONAR_ARGS \
          -Dsonar.qualitygate.name=\"${{ inputs.quality-gate-name }}\""
        fi

        if [[ "${{ inputs.event-name }}" == "pull_request" ]]; then
          SONAR_ARGS="$SONAR_ARGS \
          -Dsonar.pullrequest.key=${{ inputs.pr-number }} \
          -Dsonar.pullrequest.branch=${{ inputs.head-ref }} \
          -Dsonar.pullrequest.base=${{ inputs.base-ref }}"
          echo "Running SonarCloud in pull request mode"
        else
          echo "Running SonarCloud in full analysis mode"
        fi

        echo "sonar_args=$SONAR_ARGS" >> $GITHUB_OUTPUT

    - name: Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: ${{ steps.sonar_params.outputs.sonar_args }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}

    - name: Check quality gate
      if: ${{ inputs.check-quality-gate == 'true' }}
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
